docker-compose.yml
noxfile.py
src/race_service/commands/raceplans_commands.py
src/race_service/commands/raceplans_individual_sprint.py
src/race_service/commands/raceplans_interval_start.py
tests/contract/test_generate_raceplan_for_event_individual_sprint.py
tests/contract/test_generate_raceplan_for_event_interval_start.py
tests/files/all_expected_raceplan_individual_sprint.json
tests/files/competition_format_individual_sprint.json
tests/files/competition_format_interval_start.json
tests/files/expected_raceplan_interval_start.json
tests/integration/test_generate_raceplan.py
tests/integration/test_generate_raceplan_for_individual_sprint.py
tests/integration/test_generate_raceplan_for_interval_start.py
tests/unit/test_raceplans_individual_sprint.py
tests/unit/test_raceplans_interval_start.py

feature: add support for grouping of raceclasses

---

src/race_service/services/startlists_service.py
src/race_service/views/raceplans.py
src/race_service/views/races.py
src/race_service/views/startlists.py
tests/contract/test_raceplans.py
tests/contract/test_startlists.py
tests/integration/services/test_raceplans_service.py
tests/integration/services/test_races_service.py
tests/integration/services/test_startlist_service.py
tests/integration/test_raceplans.py
tests/integration/test_races.py
tests/integration/test_startlists.py

fix: remove POST raceplans, races and startlists

---

src/race_service/views/race_results.py

Sort results by rank (as default)

---

race_service/views/races.py
tests/integration/test_races.py

Sortere resultater (finish_results) etter plassering

---

race_service/services/races_service.py
race_service/views/race_results.py
race_service/views/races.py
race_service/views/start_entries.py
race_service/views/startlists.py
tests/contract/test_raceplans.py
tests/integration/test_races.py

update_race trigger at get_all_races feiler

---

race_service/services/time_events_service.py
race_service/views/race_results.py
race_service/views/time_events.py
tests/contract/test_time_events.py
tests/integration/test_time_events.py

delete one time event - race results not updated

---

poetry.lock
race_service/adapters/events_adapter.py
race_service/views/race_results.py
race_service/views/raceplans.py
race_service/views/races.py
race_service/views/start_entries.py
race_service/views/startlists.py
race_service/views/time_events.py
specification.yaml
tests/contract/test_generate_raceplan_for_event_individual_sprint.py
tests/contract/test_generate_raceplan_for_event_interval_start.py
tests/contract/test_generate_startlist_for_event_individual_sprint.py
tests/contract/test_generate_startlist_for_event_interval_start.py
tests/contract/test_race_results.py
tests/contract/test_raceplans.py
tests/contract/test_startlists.py
tests/contract/test_time_events.py
tests/files/.~lock.contestants_all_333.csv#
tests/integration/test_race_results.py
tests/integration/test_raceplans.py
tests/integration/test_races.py
tests/integration/test_start_entries.py
tests/integration/test_startlists.py
tests/integration/test_time_events.py

fjerne autorisasjon på utvalgte get-metoder

---

poetry.lock
pyproject.toml
race_service/app.py
race_service/gunicorn_config.py

GCP - race-service kaster error

---

.flake8
poetry.lock
race_service/views/races.py
tests/integration/test_races.py

Get race by event_id and raceclass - with details. Optimalisering - denne skal gjøre at frontend kan redusere antall backend kall på "get_race_by_id"

New method #59

---

race_service/views/race_results.py
specification.yaml
tests/integration/test_race_results.py

Hei Stig. Jeg fikk et problem med å oppdatere status på race results - her med forslag til løsning. Ser det OK ut?

New param #98

---

race_service/views/races.py
tests/contract/test_generate_startlist_for_event_individual_sprint.py
tests/contract/test_generate_startlist_for_event_interval_start.py

Sortere start-entries

---

race_service/adapters/start_entries_adapter.py
race_service/services/start_entries_service.py
race_service/views/start_entries.py

Fixes #116
Også relatert til, men fikser ikkje, feilen diskutert i #114

fix: add missing race-id to query when requesting bibs

---

race_service/services/race_results_service.py

Slå av validering for timing_point = "Template" i time-events

---

race_service/adapters/time_events_adapter.py
race_service/services/__init__.py
race_service/services/time_events_service.py
race_service/views/time_events.py
tests/contract/test_time_events.py
tests/integration/test_time_events.py

fix: time-events: throw error when bib/timing_point already exists

---

race_service/adapters/events_adapter.py
race_service/commands/raceplans_commands.py
race_service/commands/startlists_commands.py
race_service/views/time_events.py
tests/files/competition_format_individual_sprint.json
tests/files/competition_format_individual_sprint_multiple_finals_1.json
tests/files/competition_format_individual_sprint_multiple_finals_2.json
tests/files/competition_format_interval_start.json
tests/integration/test_generate_raceplan.py
tests/integration/test_generate_raceplan_for_individual_sprint_non_ranked.py
tests/integration/test_generate_raceplan_for_individual_sprint_ranked.py
tests/integration/test_generate_raceplan_for_interval_start.py
tests/integration/test_generate_startlist.py
tests/integration/test_generate_startlist_for_individual_sprint.py
tests/integration/test_generate_startlist_for_interval_start.py
tests/integration/test_raceplans.py
tests/integration/test_time_events.py
tests/unit/test_generate_startlist_for_individual_sprint.py
tests/unit/test_generate_startlist_for_individual_sprint_not_ranked.py
tests/unit/test_generate_startlist_for_interval_start.py
tests/unit/test_raceplans_individual_sprint_non_ranked.py
tests/unit/test_raceplans_individual_sprint_ranked.py
tests/unit/test_raceplans_individual_sprint_ranked_multiple_finals.py
tests/unit/test_raceplans_interval_start.py

Add support for using timezone from competition-format-service

---

race_service/views/time_events.py
tests/files/event_individual_sprint.json
tests/files/event_interval_start.json
tests/integration/test_time_events.py

Timezone is moved to event-object. Add support for using this.

---

race_service/commands/startlists_commands.py

fix: fix error message

---

race_service/services/time_events_service.py
tests/integration/test_time_events.py

fix: check only against time-events in given race

---

race_service/views/time_events.py

fix: when delete time-event, ignore if not found in results

---

race_service/commands/raceplans_commands.py
race_service/views/raceplans_commands.py
tests/integration/test_generate_raceplan.py
tests/integration/test_raceplans.py

fix: return 400 from validate raceplan when no raceclasses

---

noxfile.py
race_service/views/start_entries.py
tests/contract/test_startlists.py
tests/integration/test_start_entries.py

fix: adjust raceplans's no_of_contestants when new contestants are added or removed

---

docker-compose.yml
noxfile.py
tests/contract/test_generate_raceplan_for_event_individual_sprint.py
tests/contract/test_generate_raceplan_for_event_individual_sprint_multiple_finals.py
tests/contract/test_generate_raceplan_for_event_interval_start.py
tests/contract/test_generate_startlist_for_event_individual_sprint.py
tests/contract/test_generate_startlist_for_event_interval_start.py
tests/contract/test_race_results.py
tests/contract/test_raceplans.py
tests/contract/test_startlists.py
tests/contract/test_time_events.py

chore: drop db in contract tests to reduce contract test time by 50 %

---

race_service/adapters/events_adapter.py
race_service/views/start_entries.py
tests/contract/test_startlists.py
tests/integration/test_start_entries.py

fix: do not adjust no_of_contestants in raceplan when race is not first round

---

race_service/views/start_entries.py

fix: change calculation of no_of_contestants in race when adding/removing start-entry

---

race_service/services/__init__.py
race_service/services/raceplans_service.py

Fjern validering av raceplan ved create og update

---

race_service/adapters/start_entries_adapter.py
race_service/services/start_entries_service.py
race_service/utils/db_utils.py
race_service/views/start_entries.py
tests/integration/test_start_entries.py

fix: remove get_start_entries_by_race_id_and_bib

---

race_service/adapters/startlists_adapter.py
race_service/commands/startlists_commands.py
race_service/services/startlists_service.py
race_service/views/startlists.py
tests/integration/services/test_startlist_service.py
tests/integration/test_generate_startlist.py
tests/integration/test_generate_startlist_for_individual_sprint.py
tests/integration/test_generate_startlist_for_interval_start.py
tests/integration/test_startlists.py

feature: add bib as query param on get startlist

---

race_service/models/time_event_model.py
tests/contract/test_race_results.py
tests/contract/test_time_events.py
tests/integration/services/test_race_results_service.py
tests/integration/services/test_time_events_service.py
tests/integration/test_race_results.py
tests/integration/test_races.py
tests/integration/test_time_events.py

fix:  change registration_time format to datetime

---

race_service/commands/__init__.py
race_service/commands/startlists_commands.py
race_service/views/startlists_commands.py
tests/integration/test_generate_startlist_for_individual_sprint.py
tests/unit/test_generate_startlist_for_individual_sprint.py
tests/unit/test_generate_startlist_for_individual_sprint_not_ranked.py
tests/unit/test_generate_startlist_for_interval_start.py

chore: generalize startlist command

---

noxfile.py
race_service/adapters/time_events_adapter.py
race_service/utils/db_utils.py
race_service/views/time_events.py
tests/contract/test_time_events.py
tests/integration/test_time_events.py

get_time_events filter on bib#168
